### ISSUE TITLE
Cannot control multiple outputs on a single xnode

### ISSUE THREAD

**Issue by AL7DS** [anthonyeden/Livewire-Simple-Delegation-Switcher#4]
When attempting to control different destinations on a single xNode, ie 1,2,3,4 with 4 separate applications running on different hardware, the return status of routes made become crosslinked.  Routes change properly, but the status routine is not properly differentiating that a separate destination is being routed.

**Comment by anthonyeden** [comment]
Hi @AL7DS,
Thanks for your feedback. I haven't specifically designed it for multiple outputs - but that's something I can look into. Would you mind sharing your config(s) file so I can see what you're seeing?

**Comment by AL7DS** [comment]
Just getting back to this project.  Further observations on what is happening:
I have included the complete code I am using.  It is running on the Raspberry Pi platform.  
Currently under test, I have 2 separate Pi's running the code.  Both are controlling the same xNode, but one is looking at DST 3 and the other at DST 4.

Route selection works properly for both units, however selecting a route on either unit, causes the other display to highlight the MUTE (Source Number 0) button.

Changing the MUTE Source to 1 causes the opposite screen to show no selection when a route is made on the other, thus something in the program is returning a Source 0 string that is sent to all connected controllers. 

I am just learning Python, so backtracking your code is hit and miss for me.

By the way, have you considered using SNMP for control?, it is available in all the Xnodes.

[PiTouch.zip](https://github.com/anthonyeden/Livewire-Simple-Delegation-Switcher/files/1462034/PiTouch.zip)

**Comment by anthonyeden** [comment]
Hi @AL7DS,
Thanks - this information is very helpful. I suspect I'm getting slightly different data back from the xNode when it's a 'non-existent' stream. I'll test this out and see what I find. Can I assume this all works properly when you remove your "Mute" sources altogether?

Can you also please send me a copy of your config files for the switcher app and your xNode? Feel free to email me via my website (https://mediarealm.com.au/) if you'd rather not post that here.

I considered SNMP, but not many Livewire devices support this - whereas LWRP has been around since the very first Axia devices came out. This makes it easy for me to support lots of devices (e.g. I have people using this app with QoRs, Omnia One, etc.)

**Comment by anthonyeden** [comment]
Hi @AL7DS,

I believe this is now fixed in v1.5.0. Please try it out and let me know how you go. Thanks for taking the time to report this bug.

Thanks,
Anthony.
